version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    commit-message:
      prefix: 'upgrade'
      include: 'scope'
    labels:
      - 'dependencies'
