import './createMemoryHistorySpec.js'
import './hooksSpec.js'
import './matchSpec.js'
import './IndexRouteSpec.js'
import './LinkSpec.js'
import './RedirectSpec.js'
import './RouteSpec.js'
/* utils */
import './getParamsSpec.js'
import './isActiveSpec.js'
import './matchPatternSpec.js'
import './utilsSpec.js'
import './withRouterSpec.js'
