name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install
        run: |
          sudo apt-get install xvfb
          npm ci
          npx -y ultra-runner --raw --recursive prepublishOnly

      - name: Lint
        run: npm run lint

      - name: Type Checking
        run: npm run types:check

      - name: Tests
        run: |
          npm run test:server:ci
          xvfb-run --auto-servernum npm run test:client:ci

  publish:
    name: Publish
    needs: checks
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install
        run: |
          npm ci
          npx -y ultra-runner --raw --recursive prepublishOnly

      - name: Publish Packages
        run: |
          npx -p ./packages/sui-mono sui-mono check
          npx -p ./packages/sui-ci sui-ci release
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          GITHUB_EMAIL: cloud-accounts@scmspain.com
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
          GITHUB_USER: sui-bot
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
