name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  checks-and-release:
    name: Checks & Release
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: '.nvmrc'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install
        run: |
          sudo apt-get install xvfb
          npm install --no-save --no-fund --no-audit --legacy-peer-deps
          npx -y ultra-runner --raw --recursive prepublishOnly

      - name: Lint
        run: npm run lint

      - name: Type Checking
        run: npm run types:check

      - name: Tests
        run: |
          npm run test:server:ci
          xvfb-run --auto-servernum npm run test:client:ci

      - name: Release Packages
        if: github.ref == 'refs/heads/master'
        run: |
          npx -p ./packages/sui-mono sui-mono check
          npx -p ./packages/sui-ci sui-ci release
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          GITHUB_EMAIL: cloud-accounts@scmspain.com
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
          GITHUB_USER: sui-bot
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-tagged-packages:
    name: Publish Tagged Packages to NPM
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: '.nvmrc'

      - name: Install
        run: |
          npm install -D commander

      - name: Get Files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

      - name: Publish Packages
        run: npm run publish-tagged-packages -- --tag '${{ github.event.pull_request.head.ref }}' --files '${{ steps.files.outputs.added_modified }}'
